{{- if .Values.services.authService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "codelab.fullname" . }}-auth-service-secret
  labels:
    {{- include "codelab.labels" . | nindent 4 }}
    {{- include "codelab.componentLabels" "auth-service" | nindent 4 }}
type: Opaque
stringData:
  AUTH_SERVICE__DB_URL: {{ include "codelab.authService.dbUrl" . | quote }}
  {{- range $key, $value := .Values.services.authService.secrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
