apiVersion: v1
kind: Secret
metadata:
  name: {{ include "litellm.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "litellm.name" . }}
    helm.sh/chart: {{ include "litellm.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secretEnv.db_user | quote }}
  DB_PASSWORD: {{ .Values.secretEnv.db_password | quote }}
  DB_HOST: {{ .Values.secretEnv.db_host | quote }}
  DB_PORT: {{ .Values.secretEnv.db_port | quote }}
  DB_NAME: {{ .Values.secretEnv.db_name | quote }}
