{{- if and .Values.oidc.useSecret (not .Values.oidc.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-oidc
  labels:
    app: {{ include "mlflow.name" . }}
type: Opaque
data:
  OIDC_CLIENT_ID: {{ .Values.oidc.clientId | b64enc }}
  OIDC_CLIENT_SECRET: {{ .Values.oidc.clientSecret | b64enc }}
{{- end }}
