{{- if and .Values.s3.useSecret (not .Values.s3.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mlflow.fullname" . }}-s3
  labels:
    app: {{ include "mlflow.name" . }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.s3.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3.secretAccessKey | b64enc }}
{{- end }}
