{{- if and .Values.adminCredentials.useSecret (not .Values.adminCredentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keycloak.fullname" . }}
  labels:
    app: {{ include "keycloak.name" . }}
type: Opaque
data:
  KEYCLOAK_ADMIN: {{ .Values.adminCredentials.username | b64enc }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.adminCredentials.password | b64enc }}
{{- end }}
